version: "1.29"
database:
    image: bitnami/mysql:latest
    container_name: database
    environment:
        - MYSQL_ROOT_PASSWORD=cedrix
        - MYSQL_USERNAME=root
    volumes: 
        - ./sql:/docker-entrypoint-initdb.d 
phpServer:
    image: bitnami/php-fpm:7.4.16
    container_name: phpServer
    volumes:
        - /home/devs/teamPlanning/:/srv/http/:ro
    links:
        - database:database
    ports:
        - 9000:9000


webServer:
    image: nginx
        - /home/devs/teamplanning/:/usr/share/nginx/html/:ro
        - /home/devs/teamplanning/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
        - phpServer:phpServer
    ports:
        - 80:80
    command: nginx -c /etc/nginx/nginx.conf

phpmyadmin:
    image: bitnami/phpmyadmin:latest
    container_name: phpmyadmin
    environment: 
        - MYSQL_USERNAME=root 
    links:
        - database:database
    ports:
        - 8080:80
