database:
    image: bitnami/mysql:latest
    container_name: database
    environment:
        - MYSQL_ROOT_PASSWORD=cedrix
        - MYSQL_USERNAME=root
    volumes: 
        - ./sql:/docker-entrypoint-initdb.d
 
phpServer:
    image: bitnami/php-fpm:7.4.16
    container_name: phpServer
    volumes:
        - /home/devs/teamplanning/:/srv/http/:ro
    links:
        - database:database
    ports:
        - 9000:9000


webServer:
    image: bitnami/nginx:latest 
    container_name: webServer
    volumes:
        - /home/devs/teamplanning/:/usr/src/www
        - /home/devs/teamplanning/nginx:/etc/nginx/conf.d/
    links:
        - phpServer:phpServer
    ports:
        - 8080:80

phpmyadmin:
    image: bitnami/phpmyadmin:latest
    container_name: phpmyadmin
    environment: 
        - MYSQL_USERNAME=root 
    links:
        - database:database
    ports:
        - 8080:80
